[package]
name = "birdseye-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
thiserror = "1"
flate2 = "1"
tracing = "0.1"